Project - Associations in Rails/Active Records
smy5152/Private-events pull request #6
Opened 2021-04-19 15:34 UTC by smy5152

### ASSOCIATIONS: Project
Learn active records and rails.
Implemeting associations and advanced Model setup with many-to-many relations.

2021-04-20 19:43 UTC, enaburekhan requested changes
# Status: Changes required:wrench::hammer::full_moon:
**Hi team!
Nice start:clap::clap:.**

**Major highlights**

- The PR and readme are very descriptive:100:.

However, we still need to make a few changes to get the project approved:muscle:.

**To improve**

- [ ] App behavior

- Logged in user can create new event ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_can_create_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). Currently, I can't create new events. Kindly fix this.
- Event's index page displays past and upcoming events lists ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). As a logged-in user, I should be able to display my created events into past and upcoming events in the `Event's index` page. What's currently being displayed is the existing events.
- The event's show page displays the list of attendants ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). As a logged-in user, I should be able to achieve this from my created events. 
- The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). I should also achieve this from my created events as a logged-in user. Also fix this
- Navigation links are present at the top of the page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). Currently, there are no navigational links. Kindly fix this.

- [ ] Model

- User model: `has_many :events, foreign_key: :creator_id` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). As already highlighted in the PR, kindly fix this.
- Event model `belongs_to :creator, class_name: "User"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). Also make the necessary adjustments to this. As highlighted in the PR below.

- [ ] UsersController
`show` action

- lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). As highlighted in the PR. Kindly fix this.
- lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). Also fix this.
- lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). As already highlighted in the PR, kindly also fix this.

- [ ] Database

- the events table has column `creator_id` of type `integer`
- an index for `creator_id` column is added
- an index for `event_id` column is added to the `enrollments` table
- an index for `user_id` column is added to the `enrollments` table
Why indices for foreign keys are necessary? In short: Since the foreign key columns will be used often to retrieve related information, it's important to index them (queries on those columns will be faster with indexes). More details:
Check this [article](https://semaphoreci.com/blog/2017/05/09/faster-rails-is-your-database-properly-indexed.html) and this [article](
https://sqlperformance.com/2012/11/t-sql-queries/benefits-indexing-foreign-keys.).

- [ ] Views
- As highlighted in the PR below. Move the highlighted logic to a helper. There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. Check this [article](http://codefol.io/posts/Where-Do-I-Put-My-Code/)  and this [article](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) if you need a refresher on how to use a helper in rails. see [screen-shot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from pathwright

**Optional**

- [ ] routes only for used actions, i.e. resources :events, only: [:new, :create, :show, :index]

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

2021-04-20 19:43 UTC, enaburekhan commented on app/models/user.rb
> +  has_many :events, class_name: 'Event', inverse_of: :creator
line 4 should be:
has_many :events, foreign_key: :creator_id

2021-04-20 19:43 UTC, enaburekhan commented on app/models/event.rb
> +  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
Remove the `,  foreign_key: 'user_id'` from line 2. It's not required.

2021-04-20 19:43 UTC, enaburekhan commented on app/views/events/_form.html.erb
> +  <% end %>
Move this logic to a helper. Views are only for displaying information that became available to it from it's corresponding controllers. And not for generating it.

2021-04-20 19:43 UTC, enaburekhan commented on app/views/events/index.html.erb
> +<% end %>
Also, move this to a helper.

2021-04-20 19:43 UTC, enaburekhan commented on app/views/events/show.html.erb
> +<% end %>
Also, move this logic to a helper.

2021-04-20 19:43 UTC, enaburekhan commented on app/views/users/_form.html.erb
> +  <% end %>
Move this logic to a helper.

2021-04-20 19:43 UTC, enaburekhan commented on app/views/users/show.html.erb
> +            <% end %>
Move this logic to a helper.

2021-04-20 19:43 UTC, enaburekhan commented on app/views/users/show.html.erb
> +            <% end %>
Move this logic to a helper.

2021-04-20 19:43 UTC, enaburekhan commented on app/controllers/events_controller.rb
> +    # @event = Event.new(event_params)
Remove commented codes. Use git history if you must view previous codes

2021-04-20 19:43 UTC, enaburekhan commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
The content of the `show action` should be similar to:
@created_events = current_user.events
@past_events = current_user.attended_events.previous
@upcoming_events = current_user.attended_events.upcoming

2021-04-20 20:15 UTC, smy5152 commented on app/views/users/show.html.erb
> +            <% end %>
The project requires us to add some Logic to the VIEW to learn the concept. The other helper implementation provides the logic for the Events - Past & Upcoming

2021-04-20 20:15 UTC, smy5152 commented on app/controllers/events_controller.rb
> +    # @event = Event.new(event_params)
done

2021-04-20 20:15 UTC, smy5152 commented on app/views/users/show.html.erb
> +            <% end %>
The project requires us to add some Logic to the VIEW to learn the concept. The other helper implementation provides the logic for the Events - Past & Upcoming

2021-04-20 20:16 UTC, smy5152 commented on app/views/users/_form.html.erb
> +  <% end %>
this is default SCAFFOLD code

2021-04-20 20:16 UTC, smy5152 commented on app/views/events/show.html.erb
> +<% end %>
This is client-side Content creation - it is not mandatory to overuse helper for everything. The button optionally renders.

2021-04-20 20:18 UTC, smy5152 commented on app/views/events/index.html.erb
> +<% end %>
@username does not exist for not logged in user. It was added to prevent an error.

2021-04-20 20:18 UTC, smy5152 commented on app/views/events/_form.html.erb
> +  <% end %>
this is default SCAFFOLD code

2021-04-20 20:21 UTC, smy5152 commented on app/models/event.rb
> +  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
We are referring to the creator_id for the EVENT model - in the VIEWS.

Which is a foreign key of the USER class.

2021-04-20 20:23 UTC, smy5152 commented on app/models/user.rb
> +  has_many :events, class_name: 'Event', inverse_of: :creator
inverse_of: :creator _ automatically implies the foreign_key reference is mentioned in the EVENT model reference.

2021-04-20 21:02 UTC, smy5152 commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
Is this mandatory?

2021-04-20 21:37 UTC, smy5152 commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
This is not required: Kindly read the description on the ODIN screenshot below. The don't want us to do it...
https://github.com/smy5152/Private-events/blob/many-many/tmp/Project_%20Associa.png

2021-04-20 21:38 UTC, smy5152 commented on app/controllers/events_controller.rb
> +    # @event = Event.new(event_params)
done

2021-04-20 21:59 UTC, smy5152 commented
@enaburekhan Please remove the no-mandatory point to the appropriate section to avoid multiple reviews based on the first review points. Kindly divide into GOOD TO HAVE & MANDATORY.
The below VIEWS are already working and have been highlighted as not done in the above points?

**Steps to follow and register as a new user and ENROLL FOR events to view in the upcoming/past list:**
1. Login
2. Click My Events Link: Shows Hosted, Past, Upcoming events_: To view ATTENDEES, click an events NAME_
3. Click NEW EVENT: (Login) to HOST and event
4. Enroll for some events on the HOME PAGE/Events index: Shows - Past & Upcoming events: _To view ATTENDEES, click an events NAME_
5. Logout: You can still view Past & Upcoming events, however, cannot Enroll/Attend & cannot Host an event.

**NAVIGATION: Added to the top of the page:**
LOGIN/LOGOUT, My Events, New Event, Signup as a New User.

The EVENTS PAGE - lists ALLL EVENTS - divided in Past & Upcoming. (Logged & Guest User), to ATTEND/ENROLL you must log in. My EVENTS - Lists a Users Events - Hosted, Attending (Past & Upcoming)

I have created a CREATOR - inverse reference. It does not specify what the foreign_key should be called in the project documentation. Just the belongs_to relation.
[Documentation](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html
)

Kindly click an EVENT (I have conveniently made all Event NAMES into LINKS), clearly lists ATTENDEES.

We will try to move what we can. Creating HELPERS is not the objective of this project. And it is not mentioned anywhere in the project documentation that absolutely NO LOGIC should be in the views. In fact, this reference with Users#show is incorrect: https://github.com/smy5152/Private-events/blob/many-many/tmp/Project_%20Associa.png

INDEX: an index for `columns` - is not mentioned in any of the project descriptions/requirements.

2021-04-20 22:17 UTC, smy5152 commented on app/views/users/show.html.erb
> +            <% end %>
```
class EventsController < ApplicationController
  # before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @username = current_user.name if logged_in?
    @events_past = Event.past.all
    @events_upcoming = Event.upcoming.all
  end
end
```

2021-04-21 02:00 UTC, cyonii requested changes
### STATUS: CHANGES REQUIRED ♻️✍️

Hello team, you've shown truly a great effort since the last review. I love the energy.
However, there are still a few defects you need to fix in order to meet this project's requirements.

Keep your heads up.

#### TO IMPROVE (MANDATORY)
- [ ] As previously requested, navigation links should be present at the top of the page, this makes it easy for users to jump around your app easily. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [ ] As the previous reviewer requested, please index these following columns.
    - [ ] Events table: `user_id` column
    - [ ] Enrollment table: `event_id` column
    - [ ] Enrollment table: `user_id` column
    <br />
     Since the foreign key columns will be used often to retrieve related information, it's important to index them (queries on those columns will be faster with indexes).
More details:
    More info:
    https://semaphoreci.com/blog/2017/05/09/faster-rails-is-your-database-properly-indexed.html
    https://sqlperformance.com/2012/11/t-sql-queries/benefits-indexing-foreign-keys



#### NICE TO HAVE (OPTIONAL)
- [x]  Please always keep your repository clean and professional. Please move the images you have used in documentation of your code into `docs` directory that will live in your project's root dir.
- [ ] The Microverse URL on the  **Acknowledgement** section of your README redirects to this project's Pathwright page which is inaccessible by externals. I think it best redirects to Microverse's Github or official site.
- [ ] When a user enrolls in an event, the app should redirect them to the event show page.


See you at the top.

> #### <br>You can ping me on Slack @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) to draw my attention in case I do not respond quickly on here. I'm always available and will be glad to help.<br><br>

2021-04-21 02:00 UTC, cyonii commented on app/views/events/index.html.erb
> +      <%= my_events_link %>
- [ ] Please remove logic from view. You can always use helpers for view logic like this.

2021-04-21 07:12 UTC, Meltrust commented on app/views/events/index.html.erb
> +      <%= my_events_link %>
Done!

Also, the indexes for:

Events table: user_id column
Enrollment table: event_id column
Enrollment table: user_id column

Are done!
![image](https://user-images.githubusercontent.com/57421823/115511844-efd42400-a246-11eb-829e-c446e8a8c9e0.png)

2021-04-21 07:13 UTC, Meltrust commented
Done!

Also, the indexes for:

Events table: user_id column
Enrollment table: event_id column
Enrollment table: user_id column

Are done!
![image](https://user-images.githubusercontent.com/57421823/115512026-1f832c00-a247-11eb-8388-2e9ddf0e2352.png)

2021-04-21 07:33 UTC, mimipeshy commented
## STATUS: APPROVED 🥳 👯 
Hello team @smy5152 and @Meltrust 👋🏾 👋🏾 congratulations on making it this far in this milestone 🥇  You have made all the changes requested by the TSE. With that, I approve of this project 😄  All the best in the next milestones

Regards
__Peris Ndanu __
[GitHub ](https://github.com/mimipeshy)| [LinkedIn

2021-04-21 07:35 UTC, merged